import bcrypt from 'bcryptjs';

const data = {
  users: [
    {
      name: 'Kim',
      email: 'admin@gmail.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: true,
    },
    {
      name: 'Suzuki',
      email: 'user@gmail.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: false,
    },
  ],
  products: [
    {
      name: 'S.H.Figuarts ウマ娘 プリティーダービー ミスターシービー',
      slug: 'ミスターシービー',
      category: 'ウマ娘',
      image: '/images/shirt1.jpg',
      price: 9350,
      brand: 'S.H.Figuarts',
      rating: 4.5,
      numReviews: 8,
      countInStock: 2,
      description: 'ミスターシービー',
      isFeatured: true,
      banner: '/images/banner1.jpg',
    },
    {
      name: 'Fit Shirt',
      slug: 'fit-shirt',
      category: 'Shirts',
      image: '/images/shirt3.jpg',
      price: 5500,
      brand: 'Adidas',
      rating: 4.0,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular shirt',
      isFeatured: true,
      banner: '/images/banner2.jpg',
    },
    {
      name: 'Slim Shirt',
      slug: 'slim-shirt',
      category: 'Shirts',
      image: '/images/shirt3.jpg',
      price: 90,
      brand: 'Raymond',
      rating: 4.5,
      numReviews: 3,
      countInStock: 20,
      description: 'A popular shirt',
    },
    {
      name: 'Golf Pants',
      slug: 'golf-pants',
      category: 'Pants',
      image: '/images/pants.jpg',
      price: 90,
      brand: 'Oliver',
      rating: 2.9,
      numReviews: 13,
      countInStock: 20,
      description: 'Smart looking pants',
    },
    {
      name: 'Fit Pants',
      slug: 'fit-pants',
      category: 'Pants',
      image: '/images/pants2.jpg',
      price: 95,
      brand: 'Zara',
      rating: 3.5,
      numReviews: 7,
      countInStock: 20,
      description: 'A popular pants',
    },
    {
      name: 'フィギュアーツZERO ［超激戦］ヤマト-ONE PIECE バウンティラッシュ 5th Anniversary-',
      slug: 'classic-pants',
      category: 'OnePiece',
      image: '/images/shirt5.jpg',
      price: 11000,
      brand: 'フィギュアーツZERO',
      rating: 3.5,
      numReviews: 14,
      countInStock: 6,
      description: 'ヤマト',
    },
  ],
};

export default data;
